# Generated by Django 4.0 on 2021-12-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='category',
            new_name='question',
        ),
    ]
